In [1]:
import numpy as np
import pandas as pd
import PIL as pil
import glob
from PIL import Image
from pandas import DataFrame

In [2]:
labels = pd.read_csv("C:/Users/deli/OneDrive - Eastside Preparatory School/10th grade/Topics in Computer Science/Final Project/train/_labels.csv")
files = glob.glob("C:/Users/deli/OneDrive - Eastside Preparatory School/10th grade/Topics in Computer Science/Final Project/train/*.tif")
images = []
n = 0
for myFile in files:
    image = Image.open(myFile)
    #look up label for myFile in labels
    label = labels.iat[n, 1]
    images.append((image, label))
    n = n+1
    if n==20:
        break

print(images)
images = DataFrame(images,columns=['images','label'])
print(images)
labels.head()

#Train data
# train = []
# train_labels = []
# files = glob.glob ("/data/train/class1/*.png") # your image path
# for myFile in files:
# image = cv2.imread (myFile)
#  train.append (image)
#  train_labels.append([1., 0.])
# files = glob.glob ("/data/train/class2/*.png")
# for myFile in files:
# image = cv2.imread (myFile)
#  train.append (image)
#  train_labels.append([0., 1.])
# train = np.array(train,dtype='float32') #as mnist
# train_labels = np.array(train_labels,dtype='float64') #as mnist

[(<PIL.TiffImagePlugin.TiffImageFile image mode=RGB size=96x96 at 0x1EAA5780670>, 0), (<PIL.TiffImagePlugin.TiffImageFile image mode=RGB size=96x96 at 0x1EAA5780730>, 1), (<PIL.TiffImagePlugin.TiffImageFile image mode=RGB size=96x96 at 0x1EAA7BBC2E0>, 0), (<PIL.TiffImagePlugin.TiffImageFile image mode=RGB size=96x96 at 0x1EAA7BBC670>, 0), (<PIL.TiffImagePlugin.TiffImageFile image mode=RGB size=96x96 at 0x1EAA7BBCB20>, 0), (<PIL.TiffImagePlugin.TiffImageFile image mode=RGB size=96x96 at 0x1EAA7BBCFD0>, 0), (<PIL.TiffImagePlugin.TiffImageFile image mode=RGB size=96x96 at 0x1EAA7BC04C0>, 1), (<PIL.TiffImagePlugin.TiffImageFile image mode=RGB size=96x96 at 0x1EAA7BC0970>, 1), (<PIL.TiffImagePlugin.TiffImageFile image mode=RGB size=96x96 at 0x1EAA7BC0E20>, 0), (<PIL.TiffImagePlugin.TiffImageFile image mode=RGB size=96x96 at 0x1EAA7BC5310>, 0), (<PIL.TiffImagePlugin.TiffImageFile image mode=RGB size=96x96 at 0x1EAA7BC57C0>, 0), (<PIL.TiffImagePlugin.TiffImageFile image mode=RGB size=96x96 at

id  label
0  f38a6374c348f90b587e046aac6079959adf3835      0
1  c18f2d887b7ae4f6742ee445113fa1aef383ed77      1
2  755db6279dae599ebb4d39a9123cce439965282d      0
3  bc3f0c64fb968ff4a8bd33af6971ecae77c75e08      0
4  068aba587a4950175d04c680d38943fd488d6a9d      0

In [9]:
from numpy import asarray
for i in range(20):
    print(asarray(images.iat[i,0]))

[[[248 183 213]
  [234 167 198]
  [195 128 159]
  ...
  [225 168 187]
  [193 125 148]
  [236 161 184]]

 [[193 134 162]
  [255 223 251]
  [162 101 132]
  ...
  [190 131 153]
  [248 183 205]
  [229 155 180]]

 [[141  91 116]
  [255 218 246]
  [162 107 136]
  ...
  [219 157 182]
  [208 142 169]
  [194 124 152]]

 ...

 [[124  58  96]
  [171 101 138]
  [225 151 188]
  ...
  [186 119 152]
  [191 124 159]
  [199 132 167]]

 [[ 97  40  75]
  [ 93  31  68]
  [152  82 118]
  ...
  [194 123 157]
  [208 138 175]
  [202 131 171]]

 [[ 75  23  59]
  [105  49  84]
  [192 127 161]
  ...
  [183 109 146]
  [219 147 185]
  [148  77 119]]]
[[[242 246 245]
  [242 246 245]
  [244 246 245]
  ...
  [223 211 211]
  [234 223 221]
  [224 213 211]]

 [[244 246 243]
  [244 246 243]
  [245 245 243]
  ...
  [231 221 222]
  [214 204 203]
  [217 207 206]]

 [[246 245 241]
  [246 245 241]
  [246 245 241]
  ...
  [255 246 249]
  [242 236 238]
  [254 248 250]]

 ...

 [[236 231 228]
  [247 242 239]
  [244 240 237]
  ..